### ISSUE TITLE
error plugin load:line 316 for maya 2023

### ISSUE THREAD

**Issue by SagiriMOMO** [gameboy12615/MMD4Maya#10]
file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: ModuleNotFoundError: file C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\UI\ExplorerWindow.py line 4: No module named 'pymel'
file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Failed to run file: C:/Program Files/Autodesk/Maya2023/bin/plug-ins/MMD4Maya.py
file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316:  (MMD4Maya)

不知道自动桌又整了啥

**Comment by SagiriMOMO** [comment]
问题不是很大 更新了一下 pymel 又可以了

**Comment by SagiriMOMO** [comment]
试了一下，只导入模型没问题，但是添加动作后 log start 了 但是没有任何反应 ，没有pmx2fbx 黑窗口，cpu 也没在跑

**Comment by SagiriMOMO** [comment]
D:/3D Asset/MMDS/mmd model using/yyb kangxi Kawaii Strike/.temp_KangXi Kawaii Strike/:
# Traceback (most recent call last):

#   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\Utils.py", line 6, in ConvertToUnixPath

# TypeError: a bytes-like object is required, not 'str'
# # 
# During handling of the above exception, another exception occurred:

# Traceback (most recent call last):
#   File "C:\Program Files\Autodesk\Maya2023\Python\lib\threading.py", line 973, in _bootstrap_inner

# Exception in thread MMD4MayaProcessor#   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 191, in AsyncProcess
#     self.fbxFilePath = self.__converter.Process(self.__pmxFile, self.__vmdFileList)
#   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\FBXConverter.py", line 38, in Process
#     arguments += ConvertToUnixPath(vmdFile)#     return path.replace("\\", "/")#     self.CleanTempFiles()
# AttributeErrorself.run()
#   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
#     self.mainWindow.AsyncProcess()
#   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
#     #   File "C:\Program Files/Autodesk/Maya2023/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
#     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
: 'MainWindow' object has no attribute 'fbxFilePath'
