### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'

### ISSUE THREAD

**Issue by fukawachan** [gameboy12615/MMD4Maya#7]
I use maya 2019, and install the 2017 version mmd4maya. However, when I click 'Process', there comes a error: AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'.

**Comment by fukawachan** [comment]
Here is the specific error message:
D:/BlenderProject/.temp_Zhongli/# 
# # Exception in thread MMD4MayaProcessor:
# Traceback (most recent call last):
#   File "D:\Program Files\Autodesk\Maya2018\bin\python27.zip\threading.py", line 801, in __bootstrap_inner
#     self.run()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
#     self.mainWindow.AsyncProcess()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
#     self.CleanTempFiles()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
#     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'

**Comment by fukawachan** [comment]
Here is the specific error message:
`D:/BlenderProject/.temp_Zhongli/# 
# # Exception in thread MMD4MayaProcessor:
# Traceback (most recent call last):
#   File "D:\Program Files\Autodesk\Maya2018\bin\python27.zip\threading.py", line 801, in __bootstrap_inner
#     self.run()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
#     self.mainWindow.AsyncProcess()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
#     self.CleanTempFiles()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
#     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'`

**Comment by fukawachan** [comment]
Here is the specific error message:
> D:/BlenderProject/.temp_Zhongli/# 
# # Exception in thread MMD4MayaProcessor:
# Traceback (most recent call last):
#   File "D:\Program Files\Autodesk\Maya2018\bin\python27.zip\threading.py", line 801, in __bootstrap_inner
#     self.run()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
#     self.mainWindow.AsyncProcess()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
#     self.CleanTempFiles()
#   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
#     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'

**Comment by fukawachan** [comment]
Here is the specific error message:
> D:/BlenderProject/.temp_Zhongli/# 
> # # Exception in thread MMD4MayaProcessor:
> # Traceback (most recent call last):
> #   File "D:\Program Files\Autodesk\Maya2018\bin\python27.zip\threading.py", line 801, in __bootstrap_inner
> #     self.run()
> #   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
> #     self.mainWindow.AsyncProcess()
> #   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
> #     self.CleanTempFiles()
> #   File "D:/Program Files/Autodesk/Maya2018/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
> #     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
> AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'

**Comment by Mini-Sylar** [comment]
I use maya 2019 as well, and the 2017 wasn't working for me as well
I think the issue is with Maya 2019 not supporting Pyside1 anymore and using only Pyside2
if you want, you can check the modified version i had here

https://github.com/Mini-Sylar/MMD4Maya

installation process is the same...fingers crossed tho

**Comment by fukawachan** [comment]
Your method is really effective， my problem has been solved. Thank you very much!
