### ISSUE TITLE
Problem of MMD4Maya2022

### ISSUE THREAD

**Issue by Esquito** [gameboy12615/MMD4Maya#9]
The new branch for Maya2022 can't combine pmd and vmd files.
I can import a pmd file. However, when I try to add both pmd and vmd files, the program can't run.

**Comment by Esquito** [comment]
The error is that:
# Traceback (most recent call last):
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\threading.py", line 926, in _bootstrap_inner
#     self.run()
#   File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 26, in run
#     self.mainWindow.AsyncProcess()
#   File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 201, in AsyncProcess
#     self.CleanTempFiles()
#   File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins\MMD4Maya\Scripts\UI\MainWindow.py", line 179, in CleanTempFiles
#     shutil.rmtree(GetDirFormFilePath(self.fbxFilePath),True)
AttributeError: 'MainWindow' object has no attribute 'fbxFilePath'
